### ISSUE TITLE
For me specflow-plugin-nunit generator is not working (different solution but followed your approach)

### ISSUE THREAD

**Issue by gittadesushil** [joebuschmann/specflow-plugin-nunit3-with-global#1]
I can upload the project and show you if possible. can I do that?

**Comment by joebuschmann** [comment]
Or better yet, could you create a PR with your changes?

**Comment by gittadesushil** [comment]
@joebuschmann Thanks for reply. Please find attached modified project rathre than PR not aware about creating PR. [specflow-plugin-nunit-master-modified.zip](https://github.com/joebuschmann/specflow-plugin-nunit/files/3021508/specflow-plugin-nunit-master-modified.zip)

**Comment by joebuschmann** [comment]
I'm having a hard time understanding what the issue is and how your change addresses it. Please submit a PR with your update to the code. See the link below on creating PRs.

https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by gittadesushil** [comment]
@joebuschmann PR is submitted https://github.com/joebuschmann/specflow-plugin-nunit/pull/2. Thanks for sharing the link.

**Comment by joebuschmann** [comment]
This doesn't seem to be an issue with the plug-in code in this repo. In the example you provided, you have replaced the NUnit3 generator plug-in with your own implementation. There is either an issue with your impl, or there is an issue with the SpecFlow library.

**Comment by gittadesushil** [comment]
@joebuschmann could you please help me to fix my problem? Your help will be appreciated. Thanks in advance!
